# Generated by Django 5.2.8 on 2025-12-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_issues", "Daily Issue Report"),
                            ("daily_returns", "Daily Return Report"),
                            ("overdue_books", "Overdue Books Report"),
                            ("fines_summary", "Fines Summary"),
                            ("inventory_status", "Inventory Status"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generate_date", models.DateTimeField(auto_now_add=True)),
                ("content", models.JSONField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
