# Generated by Django 5.2.8 on 2025-12-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_rename_generate_date_report_generate_on"),
        ("users", "0002_alter_memberprofile_phone_alter_memberprofile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="generate_on",
            new_name="generated_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="content",
        ),
        migrations.RemoveField(
            model_name="report",
            name="notes",
        ),
        migrations.AddField(
            model_name="report",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="report",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="exported_pdf",
            field=models.FileField(blank=True, null=True, upload_to="reports/pdf"),
        ),
        migrations.AddField(
            model_name="report",
            name="expoted_csv",
            field=models.FileField(blank=True, null=True, upload_to="reports/csv"),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.memberprofile",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(default="Old Report", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily Issue / Return"),
                    ("monthly", "Monthly Activity"),
                    ("popular_books", "Book Popularity"),
                    ("active_members", "Active Members"),
                ],
                max_length=50,
            ),
        ),
    ]
