# Generated by Django 5.2.8 on 2025-12-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="expired_at",
            new_name="expires_at",
        ),
    ]
