# Generated by Django 5.2.8 on 2025-12-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_rename_expired_at_reservation_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="expires_at",
            new_name="expired_at",
        ),
    ]
