# Generated by Django 5.2.8 on 2025-12-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.bookmodel"
            ),
        ),
    ]
