# Generated by Django 5.2.8 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_bookcopy_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcopy",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("issued", "Issued"),
                    ("reserved", "Reserved"),
                    ("lost", "Lost"),
                    ("damaged", "Damaged"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
