# Generated by Django 5.2.8 on 2025-12-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_category_remove_bookmodel_genre_bookmodel_available_and_more"),
        ("inventory", "0003_alter_bookcopy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="shelf",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shelf'),
            preserve_default=False,
        ),
    ]
