# Generated by Django 5.2.8 on 2025-12-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookmodel_shelf"),
        ("inventory", "0003_alter_bookcopy_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.shelf"
            ),
        ),
    ]
