# Generated by Django 5.2.8 on 2025-12-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_bookmodel_shelf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmodel",
            old_name="cover",
            new_name="coverimg",
        ),
    ]
