# Generated by Django 5.2.8 on 2025-12-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_rename_cover_bookmodel_coverimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="genre",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
