# Generated by Django 5.2.8 on 2025-12-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_bookcopy_status"),
        ("users", "0002_alter_memberprofile_phone_alter_memberprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.bookcopy",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.memberprofile",
                    ),
                ),
            ],
        ),
    ]
