# Generated by Django 5.2.8 on 2025-12-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        ("users", "0002_alter_memberprofile_phone_alter_memberprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("reason", models.CharField(max_length=250)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.memberprofile",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("cash", "Cash"), ("upi", "UPI"), ("card", "Card")],
                        max_length=20,
                    ),
                ),
                ("receipt_no", models.CharField(max_length=50, unique=True)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.fine",
                    ),
                ),
            ],
        ),
    ]
