# Generated by Django 5.2.8 on 2025-12-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_fine_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
    ]
