# Generated by Django 5.2.8 on 2025-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_memberprofile_approved_memberprofile_membership_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="membership_plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("student", "Student"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
